apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: fun-facts
    role: consumer
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: fun-facts
    role: consumer
