apiVersion: v1
kind: Pod
metadata:
  name: homework-2
  namespace: homework
  annotations:
    purpose: homework
spec:
  containers:
  - name: homework-container
    image: shekeriev/k8s-appa:v1
    ports:
    - containerPort: 80
