apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  namespace: homework
  labels:
    app: hw
    ver: v1
spec:
  selector:
    app: hw
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 32000
    protocol: TCP
