apiVersion: v1
kind: Namespace
metadata:
  name: homework

---

apiVersion: v1
kind: Pod
metadata:
  name: homework-1
  namespace: homework
  labels:
    app: hw
    tier: gold
  annotations:
    purpose: homework
spec:
  containers:
  - name: homework-container
    image: shekeriev/k8s-appa:v1
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: homework-1
  namespace: homework
  labels:
    app: hw
  annotations:
    purpose: homework
spec:
  containers:
  - name: homework-container
    image: shekeriev/k8s-appa:v1
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: homework-2
  namespace: homework
  annotations:
    purpose: homework
spec:
  containers:
  - name: homework-container
    image: shekeriev/k8s-appa:v1
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: homework-2
  namespace: homework
  labels:
    app: hw
  annotations:
    purpose: homework
spec:
  containers:
  - name: homework-container
    image: shekeriev/k8s-appa:v1
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  namespace: homework
  labels:
    app: hw
    ver: v1
spec:
  selector:
    app: hw
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 32000
    protocol: TCP

---

