apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
labels:
- includeSelectors: true
  pairs:
    variant: production
resources:
- ../../base
patches:
#- path: custom-env.yaml
- path: custom-np.yaml
- path: custom-rs.yaml
